//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angielski.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Angielski.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zła wartość.
        /// </summary>
        internal static string Form1_textBox1_TextChanged_Zła_wartość {
            get {
                return ResourceManager.GetString("Form1_textBox1_TextChanged_Zła_wartość", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za dużo liter.
        /// </summary>
        internal static string Form2_buttonCheck_Click_Za_dużo_liter {
            get {
                return ResourceManager.GetString("Form2_buttonCheck_Click_Za_dużo_liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alveolus - pęcherzyk płucny
        ///respiratory system - układ oddechowy
        ///sac  - pęcherzyk
        ///tonsil - migdałek
        ///visceral - trzewny
        ///attach - przyłączyć
        ///basc - podstawa
        ///bloodstream - krwioobieg
        ///pharynx - gardło
        ///larynx - Krtań
        ///trachea - tchawica
        ///bronchi (pl), bronchus (sing)  - oskrzela
        ///bronchiole - oskrzelik
        ///cone - stożek
        ///factor - czynnik
        ///hoarseness - chrypka
        ///hurt - zranienie
        ///laryngopharynx - krtaniowa część gardła
        ///line - linia, wyścielić
        ///lobe - płat
        ///lung - płuco
        ///alveoli of the lungs - pęcherzyki plu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string slowaAng {
            get {
                return ResourceManager.GetString("slowaAng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abdomen - jama brzuszna
        ///affect - atakować
        ///ankle - kostka u nogi
        ///arm - ramię
        ///armpit - pacha
        ///bend - schylać się, zginać
        ///body - ciało
        ///bone - kość
        ///calf - łydka
        ///cavity - jama
        ///cell - komórka
        ///cheek - policzek
        ///chest - klatka piersiowa
        ///chin - broda, podbródek
        ///consist - składać się
        ///diaphragm - przepona
        ///elbow - łokieć
        ///eye - oko
        ///eyelash- rzęsa
        ///eyelid - powieka
        ///face - twarz
        ///foot, (pl. feet) - stopa, stopy
        ///forearm - przedramię
        ///forehead - czoło
        ///groin - pachwina
        ///hand - ręka, dłoń
        ///head - głowa
        ///hea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit1 {
            get {
                return ResourceManager.GetString("unit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardiovascular system - układ sercowo/naczyniowy
        ///blood vessels - naczynia krwionośne
        ///arteries - tętnice
        ///arterioles - tętniczki
        ///capillaries - naczynka
        ///venules - żyłki
        ///cone/shaped - stożkowy
        ///hollow - pusty
        ///apex - wierzchołek
        ///pericardium - osierdzie
        ///myocardium - mięsień sercowyop
        ///endocardium - wsierdzie
        ///atrium, atria, auricles - przedsionki
        ///pericarditis - zapalenie osierdzia
        ///ventricles - komory
        ///atrioventricular - przedsionkowo komorowy
        ///mitral valve, bicuspid valve - zastawka mitralna, zastawka  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit10 {
            get {
                return ResourceManager.GetString("unit10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digestive - trawienny
        ///digestive system - układ pokarmowy
        ///tissues - tkanki
        ///gastrointestinal system - Układ pokarmowy
        ///oesophagus - przełyk
        ///intestine - Jelito
        ///salivary glands - ślinianki
        ///salivary gland - gruczoł ślinowy 
        ///parotid - przyuszny
        ///submandibular - podżuchwowy
        ///sublingual glands - gruczoły podjęzykowe
        ///saliva - ślina
        ///Eustachian tube - trąbka Eustachiusza
        ///tonsils - migdałki
        ///thorax - klatka piersiowa
        ///sack - worek
        ///ovoid - jajowaty
        ///diaphragm - przepona
        ///mucous membrane - błona śluzowa
        ///hydro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit11 {
            get {
                return ResourceManager.GetString("unit11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amino acid - aminokwas
        ///antacid - związek zobojętniający kwas
        ///bile - żółć
        ///carcinoma - rak
        ///chew - żuć
        ///chyme - miazga pokarmowa
        ///colitis - zapalenie okrężnicy
        ///diarrhoea - biegunka
        ///discomfort - dolegliwość, złe samopoczucie
        ///diverticulitis - zapalenie uchyłka
        ///erosion - nadżerka
        ///exacerbation - zaostrzenie
        ///excessive - nadmierny
        ///faeces - kał, stolec
        ///fat - tłuszcz
        ///fatty acid - kwas tłuszczowy
        ///gastritis - zapalenie, nieżyt żołądka
        ///glycerol - gliceryna, glicerol
        ///haematemesis - wymioty krwawe
        ///? - ?
        ///m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit12 {
            get {
                return ResourceManager.GetString("unit12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anterior - przedni
        ///ascend - wstępować
        ///caudal - doogonowy
        ///comprise - zawierać, obejmować składać się
        ///contain - zawierać, mieścić w sobie
        ///couch - leżanka
        ///cranial - czaszkowy, głowowy
        ///descend - zstępować
        ///direct - skierować, bezpośredni
        ///distal - dystalny, dalszy
        ///dorsal - grzbietowy
        ///downwards - na/w dół, ku dołowi
        ///extend - rozciągać się, rozprzestrzeniać się
        ///forwards - naprzód, ku przodowi
        ///inferior - dolny, niższy
        ///lateral - boczny
        ///medial - środkowy
        ///parallel - równoległy
        ///pass - przejście, przech [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit2 {
            get {
                return ResourceManager.GetString("unit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blood vessel - naczynie krwionośne
        ///connective tissue - tkanka łączna
        ///dermis - skóra właściwa
        ///epidermis - naskórek
        ///epithelium - nabłonek
        ///flat - płaski
        ///hair - włosy
        ///keratinization - rogowacenie, keratynizacja
        ///layer - Warstwa
        ///mammary gland - gruczoł mleczny
        ///melanin - melanina
        ///nail - paznokieć
        ///sebaceous gland - gruczoł łojowy
        ///skin - skóra
        ///sole - podeszwa
        ///subcutaneous - podskórny
        ///sweat gland - gruczoł potowy
        ///tough - mocny wytrzymały
        ///duct - kanał
        ///cornified - zrogowaciały
        ///stratum - warstwa
        ///ger [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit3 {
            get {
                return ResourceManager.GetString("unit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acne - trądzik
        ///carbon dioxide - dwutlenek węgla
        ///crust - strup
        ///damage - szkoda, uszkodzenie, uszkodzić
        ///dermatitis - zapalenie skóry
        ///dermatomycosis - grzybica
        ///dissolved - rozpuszczony
        ///ear wax - woskowina uszna
        ///eczema - egzema
        ///erythema - rumień
        ///evaporate - parować, ulatniać się
        ///excessive - nadmierny
        ///excoriation - otarcie skóry, zadrapanie
        ///excretory organ - organ wydalniczy
        ///expose - wystawić, narazić
        ///fissure - szczelina, pęknięcie
        ///furuncle - czyrak nogi
        ///injury - zranienie, uszkodzenie
        ///irritati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit4 {
            get {
                return ResourceManager.GetString("unit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abdominopelvic cavity - jama brzuszno/miednicza
        ///bound - ograniczać, wiązać
        ///brain - mózg
        ///cranial cavity - jama czaszkowa
        ///feverish - gorączkowy
        ///heart - serce
        ///large intestine - jelito grube
        ///liver - wątroba
        ///lung - płuco
        ///pancreas - trzustka
        ///pelvis - miednica
        ///peritoneum - otrzewna
        ///rectum - odbyt
        ///reproductive organs - organy rozrodcze
        ///rib - żebro
        ///slightly - nieznacznie
        ///small intestine - jelito cienkie
        ///sort out - rozwiązać
        ///spinal column - kręgosłup
        ///spleen - śledziona
        ///sternum - mostek
        ///stomach -  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit5 {
            get {
                return ResourceManager.GetString("unit5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appendicular - odnoszący się do kończyn
        ///axial - osiowy
        ///carpal - nadgarstkowy
        ///cervical - szyjny
        ///clavicle - obojczyk
        ///coccyx - kość guziczna, kość ogonowa
        ///cranium - mózgoczaszka
        ///femur - kość udowa
        ///fibula - kość strzałkowa
        ///girdle - obręcz
        ///humerus - kość ramieniowa
        ///lumbar - lędźwiowy
        ///metacarpal - śródręczny
        ///metatarsal - śródstopowy
        ///patella - rzepka kolanowa
        ///phalanges(pl.) phalanx(sing.) - paliczki
        ///radius - kość promieniowa
        ///sacrum - kość krzyżowa
        ///scapula - łopatka
        ///skull - czaszka
        ///tibia - kość  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit6 {
            get {
                return ResourceManager.GetString("unit6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alveolus - pęcherzyk płucny
        ///respiratory system - układ oddechowy
        ///sac  - pęcherzyk
        ///tonsil - migdałek
        ///visceral - trzewny
        ///attach - przyłączyć
        ///basc - podstawa
        ///bloodstream - krwioobieg
        ///pharynx - gardło
        ///larynx - Krtań
        ///trachea - tchawica
        ///bronchi (pl), bronchus (sing)  - oskrzela
        ///bronchiole - oskrzelik
        ///cone - stożek
        ///factor - czynnik
        ///hoarseness - chrypka
        ///hurt - zranienie
        ///laryngopharynx - krtaniowa część gardła
        ///line - linia, wyścielić
        ///lobe - płat
        ///lung - płuco
        ///alveoli of the lungs - pęcherzyki plu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit7 {
            get {
                return ResourceManager.GetString("unit7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to respiration - oddychanie
        ///reversible - odwracalny
        ///absorb - wchłaniać
        ///absorption - wchłanianie
        ///sacs - woreczki
        ///diffuses - przenikać, rozproszony, rozpraszać
        ///accessory - dodatkowy, pomocniczy
        ///accessory organs - poboczne organy
        ///intercostal muscles - mięśni międzyżebrowych
        ///intercostal - międzyżebrowe
        ///involve - wciągnąć (w proces chorobowy)
        ///ribs - żebra
        ///blaish - niebieskawy
        ///capillary - naczynie włosowate
        ///consecutive - kolejny
        ///distension - rozszerzanie
        ///enlarge - powiększyć
        ///exhale - wydychać
        ///distr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit8 {
            get {
                return ResourceManager.GetString("unit8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anemia - anemia
        ///fluid - płyn
        ///carbon dioxide - dwutlenek węgla
        ///plasma - osocze krwi
        ///carbohydrates - węglowodany
        ///dissolved - rozpuszczony
        ///dissolve - rozpuścić
        ///dizziness - zawrót głowy
        ///suspended - zawieszony
        ///lung capillary - kapilary płuc
        ///granulocytes - granulocyty
        ///basophils - bazofile, leukocyt zasadochłonny
        ///eosinophils - granulocyt eozynochłonny
        ///neutrophils - neutrofil, granulocyt obojętnochłonny
        ///monocytes - monocyty
        ///ingest - przyjmować pokarm,
        ///blood coagulation, blood clotting - krzepnięcia  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unit9 {
            get {
                return ResourceManager.GetString("unit9", resourceCulture);
            }
        }
    }
}
